### ISSUE TITLE
XA resource 'xxxxx': commit for XID 'XID:xxxxx' raised -6: the XA resource did not expect this command in the context.

### ISSUE THREAD

**Issue by sarathccs** [atomikos/transactions-essentials#114]
I get Heuristic termination of XAResourceTransaction with state HEUR_HAZARD While with below error
XA resource 'xxxxx': commit for XID 'XID:xxxxx' raised -6: the XA resource did not expect this command in the context.
Caused by ORA-02056:2PC: k2lcom: bad two-phase command number rdonly from coord

My questions are
1.why the transaction manager tries to commit and raising heuristic exception if there was an error for a XA resource? Why dont rollback the entire transaction?
2. Is it because of this particular error? If so what is special for this?
Using Atomikos : 5.0.6

Kindly help with it
Thanks
Sarath

**Comment by sarathccs** [comment]
Using Atomikos : 5.0.6.

**Comment by GuyPardon** [comment]
Hi,

This can happen if recovery already committed in the background. Normally you can ignore this warning.

If you want to be 100% sure then we have a tracing and monitoring module in our commercial edition. A free trial is available, let me know if that sounds good.

Guy

**Comment by sarathccs** [comment]
This is not a warning, this is an 'ERROR' printed in the log. Which no application team would want to see

**Comment by GuyPardon** [comment]
I understand if this is frustrating, but we looked into this for you and in this particular case I am pretty sure you can ignore it. 

If you want a hardened version of our product with more refined error handling then I suggest looking at the commercial distribution. It contains 100s of improvements and professional monitoring and tracing. Or you can build your own by cloning our GitHub repo.

**Comment by sarathccs** [comment]
Thanks @GuyPardon 
Can you please keep this issue open so that you can fix it may be in the next version. Because, we can't go to Prod with an 'ERROR' log especially with out a reasonable root cause.

**Comment by GuyPardon** [comment]
Reopening on request.

**Comment by GuyPardon** [comment]
@sarathccs when are you planning to go to PROD?

**Comment by GuyPardon** [comment]
Fixed.

**Comment by sarathccs** [comment]
Thanks a lot @GuyPardon . Could you please tell me the fixed version.

**Comment by sarathccs** [comment]
This comes with 5.0.8 as well. This error rollbacks the transaction.

**Comment by GuyPardon** [comment]
I have reopened for you, but it looks like this is turning into a support issue (which we can only do for customers). You can apply here:

https://www.atomikos.com/Main/ExtremeTransactionsFreeTrial

Thanks

**Comment by sarathccs** [comment]
This is still an issue for us. We were using 3.9.3 version and it was perfect. But upgrading spring and hibernate to 5.x versions forced us to move to atomikos 5.x. My question can we still use atomikos 3.9.3 with spring hibernate 5x version. If possible any sample project available please.

**Comment by sarathccs** [comment]
This has been resolved. We are running multi node and was using same transaction manager unique name(com.atomikos.icatch.tm_unique_name) and all connecting to same oracle data source. It was same setup with atomikos 3x version where it was not making issues. But here with latest version its a problem since its creating conflicts with transaction ids created by different nodes(same ids from different nodes will be recognised as same by oracle as we use same name) . So fixed  by giving unique transaction manager names for each nodes.
